config/routes.rb
Rails.application.routes.draw do

  resources :leads
  resources :posts
  root 'home#index'
  get 'download_pdf', to: "home#download_pdf"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
    validates :name, :presence => true 
    validates :email, :presence => true, :uniqueness => true
    validates :stack, :presence => true
    # validates :email, :uniqueness => true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	protected 
		def authenticate
	    authenticate_or_request_with_http_basic do |name, password|
	      name == 'ornitorrinco' && password == 'secret123'
	    end 
	  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @posts = Post.all
    @lead = Lead.new
  end
  
  def download_pdf
    send_file "#{Rails.root}/app/assets/docs/6_dicas_valiosas_fidelizar_clientes_ebook.pdf", type: "application/pdf", x_sendfile: true
  end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:index, :show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)
    @lead.ip = request.remote_ip

    respond_to do |format|
      if @lead.save
        format.html { redirect_to root_path, notice: 'Obrigado! Clique aqui e baixe agora nosso material :)' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:name, :email, :stack, :city, :state)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:create, :edit, :update, :destroy]



  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :slug, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }
    
    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }
    
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    
    markdown.render(text).html_safe
  end

  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
  
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
  <% flash.each do |key, value| %>
    <div class="row col-md-12">
      
      <div class="alert alert-success alert-dismissible text-center top-buffer hidden-xs" role="alert">
        <strong>
          <%= link_to value, download_pdf_path, target:"_blank" %>
        </strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
      </div>
      
      <div class="alert alert-success alert-dismissible text-center visible-xs" role="alert">
        <strong>
          <%= link_to value, download_pdf_path, target:"_blank" %>
        </strong>
        
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
      </div>
    </div>
  <% end %>

<div class="row orange-section hidden-xs">
  <div class="col-md-6 col-md-offset-6" style="margin-bottom:30px;">
    <h3 style="color:white;">Faça seu cadastro e receba nosso e-book exclusivo! <strong>É grátis!</strong></h3> 
    <%- model_class = Lead -%>  
    <%= render :partial => '/leads/form' %>
  </div>
</div>

<div class="row">
  <div class="container post-list-home">
    <div class="col-md-12">
      <% @posts.order('created_at DESC').each do |post| %>
        <div class="row">
          <div class="col-md-12">
            <h2><%=link_to post.title, post, class:'post-title'%></h2>
            
          </div>
          
          <div class="col-md-12">
            <h5 class="text-muted"><%= post.created_at %></h5>
          </div>
          
          <div class="col-md-12" style="font-size:18px;">
            <%=link_to markdown(post.slug.truncate(220)), post, class:'post-text'%>
          </div>
        </div>
      <% end %>
      
      
      
    </div>
    
  </div>
</div>

<div class="row" id="contato" style="margin-bottom:50px">
  <div class="container text-center">
    <h1><strong>Contato</strong></h1>
    
    <h3 class="hidden-xs">Prepare-se para mudar a forma como você conhece o setor de vendas! 
    Reinvente-se, abra sua mente, tenha conteúdo de qualidade gratuito com possibilidade de ultrapassar barreiras. 
    Deixar de apenas vender, mas entregar soluções de problemas para seus clientes.</h3> 
    
    <h4 class="visible-xs">Prepare-se para mudar a forma como você conhece o setor de vendas! 
    Reinvente-se, abra sua mente, tenha conteúdo de qualidade gratuito com possibilidade de ultrapassar barreiras. 
    Deixar de apenas vender, mas entregar soluções de problemas para seus clientes.</h4> 
    
    <h3 class="hidden-xs">
      <strong><%= mail_to 'contato@alemdasvendas.com' %></strong>
    </h3>
    
    <h4 class="visible-xs">
      <strong><%= mail_to 'contato@alemdasvendas.com' %></strong>
    </h4>
  </div>
  
</div>

<div class="container">
  <div class="row blue-section hidden-xs">
    <div class="col-md-6 col-md-offset-6" style="margin-bottom:30px;">
        <h3 style="color:white;">Faça seu cadastro e receba nosso e-book exclusivo! <strong>É grátis!</strong></h3> 
        <%- model_class = Lead -%>  
        <%= render :partial => '/leads/form' %>
    </div>
  </div>
</div>

<div class="row blue-section-xs visible-xs" id="blue-form">
  <div class="col-xs-12" style="margin-bottom:30px;">
    <h3 style="color:white;">Faça seu cadastro e receba nosso e-book exclusivo! <strong>É grátis!</strong></h3> 
    <%- model_class = Lead -%>  
    <%= render :partial => '/leads/form' %>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" 
    aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
       <%= image_tag("pop_up.png", height: '340') %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left btn-lg" data-dismiss="modal" aria-hidden="true">
            <span class="text-muted">Lembrar Depois</span>
        </button>
        
          <%= link_to 'Sim, Eu Quero!', "#contato", class:'btn btn-success btn-lg', style:'color:white;font-weight:bold' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>AlémDasVendas</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width" intitial-scale="1" maximum-scale="1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <% if Rails.env.production? %>
      <script type="text/javascript">
        // GOOGLE ANALYTICS
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-103057361-1', 'auto');
      </script>
    <% end %>
</head>

<body>
    <div class="container">

        <nav class="navbar navbar-default navbar-fixed-top visible-xs">
            <div class="container-fluid">
                <div class="navbar-header text-center">
                    <%= link_to image_tag("logo.png", height: '45'), root_path, class:"brand" %>
                </div>
            </div>
        </nav>
        
        <nav class="navbar navbar-default navbar-fixed-top hidden-xs">
            <div class="container">
                
                <div class="navbar-header">
                    <%= link_to image_tag("logo.png", height: '45'), root_path, class:"brand" %>
                </div>
                
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#contato" class="text-muted">Contato</a></li>
                </ul>
                
            </div>
        </nav>
        
        <div class="row">
            <%= link_to image_tag("main_banner.jpg",class:"img-responsive"), "#blue-form"  %>
        </div>
        
        <div class="row visible-xs" style="margin:10px 0 10px 0;">
          <div class="col-xs-12 text-center">
              <%= link_to root_path+"#blue-form", class:"btn btn-success btn-lg", style:"font-weight:bold;" do %>
                <span class="glyphicons glyphicons-hand-right"></span>Aumente Suas Vendas!
              <% end %>
          </div>
        </div>
        
        <%= yield %>
        
        <div class="container hidden-xs" style="background-color:grey" >
          <div class="container text-center" style="margin:15px 0 15px 0;">
            <%= link_to image_tag("facebook.png", height:"60"), 
              'https://web.facebook.com/alemdasvendas/', target:"_blank" %>
            <%= link_to image_tag("instagram.png", height:"60"), 
              'https://www.instagram.com/alemdasvendas/', target:"_blank" %>
            <%= link_to image_tag("google_plus.png", height:"60"), 
              'https://plus.google.com/113312984020872492243?hl=pt_BR', target:"_blank"%>
            <%= link_to image_tag("twitter.png", height:"60"), 
              'https://twitter.com/Alemdas_Vendas', target:"_blank" %>
          </div>
        </div>
        
        <div class="row visible-xs" style="background-color:grey" >
          <div class="col-md-12 text-center" style="margin:15px 0 15px 0;">
            <%= link_to image_tag("facebook.png", height:"60"), 
              'https://web.facebook.com/alemdasvendas/', target:"_blank" %>
            <%= link_to image_tag("instagram.png", height:"60"), 
              'https://www.instagram.com/alemdasvendas/', target:"_blank" %>
            <%= link_to image_tag("google_plus.png", height:"60"), 
              'https://plus.google.com/113312984020872492243?hl=pt_BR', target:"_blank"%>
            <%= link_to image_tag("twitter.png", height:"60"), 
              'https://twitter.com/Alemdas_Vendas', target:"_blank" %>
          </div>
        </div>
        
        
    </div>


</body>

</html>

app/views/leads/_form.html.erb
<%= form_for @lead, :html => { :class => "leads-form",:style =>"margin-top:30px;"  } do |f| %>

  <% if @lead.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @lead.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label 'Nome Completo' %>
      <%= f.text_field :name, :class => 'form-control' %>
      <%=f.error_span(:name) %>
  </div>
  
    <div class="form-group">
      <%= f.label 'Email' %>
      <%= f.text_field :email, :class => 'form-control' %>
      <%=f.error_span(:email) %>
  </div>
  
  <div class="form-group">
      <%= f.label 'Profissão' %>
      <%= f.text_field :stack, :class => 'form-control' %>
      <%=f.error_span(:stack) %>
  </div>

  <%= f.submit 'Registrar-se!', :class => 'btn btn-success btn-lg pull-right',:style => "font-weight:bold;" %>
   
  </div>

<% end %>

app/views/leads/edit.html.erb
<%- model_class = Lead -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/leads/index.html.erb
<%- model_class = Lead -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> - Total: <%= @leads.count %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:stack) %></th>
      <th><%= model_class.human_attribute_name(:ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= link_to lead.id, lead_path(lead) %></td>
        <td><%= lead.name %></td>
        <td><%= lead.email %></td>
        <td><%= lead.stack %></td>
        <td><%= lead.ip %></td>
        <td><%=l lead.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      lead_path(lead), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lead_path(lead), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lead_path(lead),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lead_path,
            :class => 'btn btn-primary' %>

app/views/leads/new.html.erb
<div class="container">
  <h1></h1>
  <div class="col-md-12 text-center">

    <div class="row col-md-12 text-center"> 
      <h4>Prepare-se para mudar a forma como conhece o setor de vendas! Reinvente-se, abra sua mente, consuma conteúdo de qualidade gratuito com possibilidades de ultrapassar barreiras. Deixar de apenas vender, mas entregar soluções de problemas para seus clientes.</h4>
      <p></p>
    </div> 

    <div class="row col-md-8 col-md-offset-1">
      <%- model_class = Lead -%>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/leads/show.html.erb
<%- model_class = Lead -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @lead.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @lead.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stack) %>:</strong></dt>
  <dd><%= @lead.stack %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ip) %>:</strong></dt>
  <dd><%= @lead.ip %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              leads_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lead_path(@lead), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lead_path(@lead),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

  <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.gollum_editor :body %>
    </div>
    <%=f.error_span(:body) %>
  </div>
  <div class="form-group">
    <%= f.label :slug, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :slug, :class => 'form-control' %>
    </div>
    <%=f.error_span(:slug) %>
  </div>
  <div class="form-group">
    <%= f.label :tags, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tags, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tags) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          post_path(@post),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-xs btn-danger' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="container row page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="container row col-md-12">
<% @posts.each do |post| %>
  <div class="row col-md-12">
    <div class="post-list">
      <h3 class"post-title"><%= post.title %></h3>
      <small>em <%= post.created_at.to_s(:post) %> por AlémDasVendas</small>
      <p><%= markdown(post.body) %></p>
    </div>
    <%= link_to "Leia mais", post_path(post) %>
  </div>
<% end %>
</div>

app/views/posts/list.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:slug) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.slug %></td>
        <td><%= post.tags %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<style>
.top-buffer { 
  margin-top:60px; 
}
</style>

<%- model_class = Post -%>

<div class="row top-buffer">
    <div class="col-md-8 col-md-offset-2">
        <h1 class="post-title"><%= @post.title %></h1>  
        <small>em <%= @post.created_at.to_s(:post) %> por AlémDasVendas</small>
        <p><%= markdown(@post.body) %></p>        
    </div>
</div>

<div class="row top-buffer">
    <div class="col-md-8 col-md-offset-2">
       <%= link_to 'Voltar', root_path, class:'btn btn-success btn-lg pull-right', style:'color:white;' %>   
    </div>
</div>









     